name: TileDB-Cloud-PythonDB CI

on:
  push:
    tags:
      - '*'
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  TileDB-Cloud-PythonDB-Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Install pytest
        run: |
          pip install --upgrade pip wheel pytest pytest-cov setuptools setuptools-scm

      - name: Run tests
        env:
          DB_TOKEN: ${{ secrets.DB_TOKEN }}
        run: |
          pytest -s
